version: "3.9"

services:

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - apps
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
    volumes:
      - ../:/app
      # Adicione aqui abaixo os arquivos de configuração do nginx dos seus projetos.
      # - ./nginx/projeto.conf:/etc/nginx/conf.d/projeto.conf
    ports:
      - "80:80"
    hostname: projeto.local
    networks:
      default:
        ipv4_address: 172.10.0.101

  apps:
    build:
      context: ./php
      dockerfile: Dockerfile_php81 # Use o arquivo de acordo com a versão php pretendida.
    image: local
    container_name: apps
    working_dir: /app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    volumes:
      - ../:/app
      - ./php/php81-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    hostname: apps
    networks:
      default:
        ipv4_address: 172.10.0.10
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # Adicione aqui abaixo no caso de usar mais de um projeto o dns local e coloque o IP do container do webserver: 172.10.0.101
      #- "financiamento.local:172.10.0.101"

  db:
    image: mysql:8.0
    container_name: mysql    
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    user: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      TZ: Brazil/East
    networks:
      default:
        ipv4_address: 172.10.0.11

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 256M
    expose:
      - 6379
    networks:
      default:
        ipv4_address: 172.10.0.12

networks:
  default:
    driver: bridge
    name: local
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1
